apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: <access>
  AWS_SECRET_ACCESS_KEY: <secret>
kind: Secret
metadata:
  creationTimestamp: null
  name: yc-credentials
  namespace: app

  # Создавал секрет через kubectl
