apiVersion: v1
data:
  .dockerconfigjson: <base64>
kind: Secret
metadata:
  creationTimestamp: null
  name: ycr-secret
  namespace: app
type: kubernetes.io/dockerconfigjson

# Создавал секрет через kubectl
